version: '3.2'

networks:
  shag:
    external:
      name: shag

services:
  frontend:
    container_name: diplom-front
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - shag
    depends_on:
      - backend
    ports:
      - 8010:80

  backend:
    container_name: diplom-back
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - shag
    depends_on:
      - cache
      - db

  cache:
    container_name: diplom-cache
    image: memcached:1.5-alpine
    networks:
      - shag
  db:
    container_name: doplom-db
    image: mysql:latest
    env_file:
      - ./.env-mysql
    networks:
      - shag
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
    driver: local


