services:
  content.controller.index:
    class: App\ContentBundle\Controller\ContentController
    public: true
    arguments:
      - '@content.storage.fake'
    calls:
      - [setContainer, ['@Psr\Container\ContainerInterface']]

  content.storage.fake:
    class: App\ContentBundle\Storage\HardStorage
    arguments:
      - '@doctrine'

