<?php

namespace ContainerDlQ0SdL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContent_Controller_IndexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'content.controller.index' shared service.
     *
     * @return \App\ContentBundle\Controller\ContentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/ContentBundle/Controller/ContentController.php';
        include_once \dirname(__DIR__, 4).'/src/ContentBundle/Storage/StorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ContentBundle/Storage/HardStorage.php';

        $container->services['content.controller.index'] = $instance = new \App\ContentBundle\Controller\ContentController(new \App\ContentBundle\Storage\HardStorage(($container->services['doctrine'] ?? $container->getDoctrineService())));

        $instance->setContainer($container);

        return $instance;
    }
}
