<?php

namespace ContainerDlQ0SdL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\LoadDataCommand' shared autowired service.
     *
     * @return \App\Command\LoadDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/LoadDataCommand.php';

        $container->privates['App\\Command\\LoadDataCommand'] = $instance = new \App\Command\LoadDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('data:load-data');

        return $instance;
    }
}
