<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlQ0SdL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlQ0SdL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDlQ0SdL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDlQ0SdL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDlQ0SdL\App_KernelDevDebugContainer([
    'container.build_hash' => 'DlQ0SdL',
    'container.build_id' => 'f7a4ed8c',
    'container.build_time' => 1607626111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlQ0SdL');
