<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'login' => [[], ['_controller' => 'content.controller.index:show'], [], [['text', '/content/']], [], []],
];
